### ISSUE TITLE
Error after entering pymusiclooper in cmd

### ISSUE THREAD

**Issue by Aeropro4** [arkrow/PyMusicLooper#16]
*Before continuing with the bug report, does updating to the latest version fix this issue?* 
No

**Describe the bug**
It was working just fine for a few weeks but recently it started to give this error: And I reinstalled python, pip deleted and reinstalled all libraries but none worked just this same error

**Debugging Information**
Traceback (most recent call last):
  File "frozen runpy", line 198, in _run_module_as_main
  File "frozen runpy", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\pymusiclooper.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\pymusiclooper\__main__.py", line 3, in <module>
    from .cli import cli_main
  File "C:\Program Files\Python311\Lib\site-packages\pymusiclooper\cli.py", line 20, in <module>
    from .core import MusicLooper
  File "C:\Program Files\Python311\Lib\site-packages\pymusiclooper\core.py", line 6, in <module>
    import taglib
ImportError: DLL load failed while importing taglib: The specified module could not be found

**Expected behavior**
U know to run normally 

**Environment Information (please complete the following information):**
- Windows 10
- PyMusicLooper version 3.1.0.0 (I can't use pymusiclooper --version cause of it): 
- Is FFmpeg installed and working? 
Yeah its in PATH

**Additional context**
I don't have very much of coding knowledge so i can't interpret it very much 
and i tried both pipx and pip installation methods but both gives the same thing

**Comment by Aeropro4** [comment]
Nvm it was just a mere corruption in visual redistributables nothing more
