### ISSUE TITLE
installing via pip results in broken version

### ISSUE THREAD

**Issue by gingerbeardman** [arkrow/PyMusicLooper#28]
*Before continuing with the bug report, does updating to the latest version fix this issue?* [Yes/No]

No

**Describe the bug**
installing via pip results in broken version

**Debugging Information**
```
% pymusiclooper --version
Traceback (most recent call last):
  File "/opt/homebrew/bin/pymusiclooper", line 5, in <module>
    from pymusiclooper.__main__ import cli
  File "/opt/homebrew/lib/python3.11/site-packages/pymusiclooper/__main__.py", line 3, in <module>
    from .cli import cli_main
  File "/opt/homebrew/lib/python3.11/site-packages/pymusiclooper/cli.py", line 20, in <module>
    from .core import MusicLooper
  File "/opt/homebrew/lib/python3.11/site-packages/pymusiclooper/core.py", line 18, in <module>
    taglib = lazy.load("taglib")
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lazy_loader/__init__.py", line 205, in load
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/taglib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6TagLib10StringList6appendERKNS_6StringE'
```

**Expected behavior**
- should work

**Environment Information (please complete the following information):**
- OS: macOS 14.2.1 Sonoma
- PyMusicLooper version being used (execute `pymusiclooper --version` in the terminal if unsure): 3.2.2
- Is FFmpeg installed and working? (execute `ffmpeg --version` in the terminal if unsure): Yes

**Additional context**

**Comment by gingerbeardman** [comment]
Reading seems to indicate this may be an issue with parts of the package being built to the wrong architecture.

**Comment by arkrow** [comment]
I believe this is the same issue as #17. Unfortunately, I cannot reproduce this issue as I do not have an M1-based Mac, but you can try re-installing `pymusiclooper` and all its dependencies from source in pipx using (based on your provided commands):

```bash
/opt/homebrew/opt/python@3.11/bin/python3.11 -m pipx runpip pymusiclooper install --ignore-installed --no-binary :all: pymusiclooper
```

Let me know if this works for you.

By the way, there shouldn't be a need for enabling the `--pre` pip flag (to fetch newer versions in pre-release stage) unless you are installing PyMusicLooper in a Python 3.12 environment, since numba's Python 3.12 supported version is currently in pre-release status (0.59.0rc1).

**Comment by gingerbeardman** [comment]
Hi, that's pretty much what I did at https://github.com/arkrow/PyMusicLooper/issues/28#issuecomment-1892090390 and it results in a broken binary.

I just did your exact command and the same.

So, I will just continue to use 2.5.3 as it works for me.

**Comment by arkrow** [comment]
Thanks for mentioning my tool @gingerbeardman. I'm glad you found it useful!

I've pushed a new release providing a workaround for this issue. Could you test the latest release (v3.2.3) and let me know if it fixes the issue for you?

While this release does not solve the root cause of the taglib ImportError problem (that issue is currently open at the library here: https://github.com/supermihi/pytaglib/issues/114), it isolates it to the tagging functions/commands only, so the rest of the library should be unaffected.

**Comment by arkrow** [comment]
This should be fixed as of [pytaglib's 3.0.0 release](https://github.com/supermihi/pytaglib/blob/main/CHANGELOG.md) which now natively builds an arm64-compatible macos package. The workarounds above are no longer needed and tagging should work as expected.
